name: Setup
description: "Setup actions"
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: "lts/*"
        cache: "npm"
