name: Deploy to Github Pages

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: "npm"
      - name: Add .env files
        run: echo ${{secrets.ENV_WEBSITE_BASE64}} | base64 -d > ./packages/website/.env
#      - name: Setup tmate session
#        uses: mxschmitt/action-tmate@v3
      - name: Build
        env:
          CI: true
        run: |
          yarn
          yarn workspace @package/dump-pow-contracts compile
          yarn workspace @package/dump-pow-website run build
          yarn workspace @package/dump-pow-website run export
          cp ./packages/website/CNAME ./packages/website/out/CNAME
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages/website/out
